- name: Создать бакеты MinIO
  hosts: nodes
  gather_facts: false
  become: true
  tasks:
    - name: Импорт задач создания бакетов MinIO
      ansible.builtin.import_role:
        name: .
        tasks_from: create_minio_buckets.yml
