---
- name: Создать каталог конфигурации MinIO
  ansible.builtin.file:
    path: "{{ minio_etc_dir }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0750"

- name: Проверить корректность режима кластера
  ansible.builtin.assert:
    that:
      - (minio_cluster_mode == 'Single Instance') or ((minio_cluster_mode == 'High Availability') and (groups[minio_cluster_nodes_group] | default([]) | length) >= 1)
    fail_msg: "Некорректные параметры кластера MinIO"

- name: Сгенерировать файл окружения MinIO
  ansible.builtin.template:
    src: minio.env.j2
    dest: "{{ minio_server_envfile }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0640"
  notify: Перезапустить службу MinIO

- name: Разместить unit systemd для MinIO
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    owner: root
    group: root
    mode: "0644"
  notify: Перезапустить службу MinIO

- name: Включить и запустить службу MinIO
  ansible.builtin.systemd:
    name: minio
    enabled: true
    state: "{{ (minio_autostart | default(true)) | ternary('started', 'stopped') }}"
    daemon_reload: true
