---
- name: Создать каталог конфигурации MinIO
  ansible.builtin.file:
    path: "{{ minio_etc_dir }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0750"

- name: Проверить корректность режима кластера
  ansible.builtin.assert:
    that:
      - (minio_cluster_mode == 'Single Instance') or ((minio_cluster_mode == 'High Availability') and (groups[minio_cluster_nodes_group] | default([]) | length) >= 1)
    fail_msg: "Некорректные параметры кластера MinIO"

- name: Сгенерировать файл окружения MinIO
  ansible.builtin.template:
    src: minio.env.j2
    dest: "{{ minio_server_envfile }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0640"
  notify: Перезапустить службу MinIO

- name: Разместить unit systemd для MinIO
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    owner: root
    group: root
    mode: "0644"
  register: _minio_service_unit
  notify: Перезапустить службу MinIO

- name: Включить и запустить службу MinIO
  ansible.builtin.systemd:
    name: minio
    enabled: true
    state: "{{ (minio_autostart | default(true)) | ternary('started', 'stopped') }}"

- name: Открыть порты MinIO в Firewalld (Red OS)
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ minio_server_port | default('9000') }}/tcp"
    - "{{ minio_console_port | default('9001') }}/tcp"
  when: ansible_distribution.split(' ') | first | lower == 'red'

- name: Полностью разрешить межкластерный трафик между нодами MinIO (Red OS)
  firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ hostvars[item].ansible_host | default(hostvars[item].ansible_default_ipv4.address) }}" accept'
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ groups[minio_cluster_nodes_group | default('node')] | default([]) }}"
  when: 
    - ansible_distribution.split(' ') | first | lower == 'red'
    - (groups[minio_cluster_nodes_group | default('node')] | default([]) | length) > 1
    - item != inventory_hostname

- name: Set SELinux context for node_exporter executable
  community.general.sefcontext:
    target: "{{ node_exporter_path }}/{{ node_exporter_name }}/node_exporter"
    setype: bin_t
    state: present
  register: selinux_fcontext
  when: 
    - ansible_distribution.split(' ') | first | lower == 'red'

- name: Apply SELinux context to node_exporter executable
  ansible.builtin.command:
    cmd: "restorecon -v {{ node_exporter_path }}/{{ node_exporter_name }}/node_exporter"
  when: 
    - ansible_distribution.split(' ') | first | lower == 'red'
    - selinux_fcontext.changed
  notify: restart_node_exporter
