---
- name: Set insecure mc command
  set_fact:
    mc_command: "{{ minio_client_bin }} --insecure"
  when: not minio_validate_certificate

- name: Set secure mc command
  set_fact:
    mc_command: "{{ minio_client_bin }}"
  when: minio_validate_certificate

- name: Configure minio connection alias
  command: "{{ mc_command }} alias set {{ minio_alias }} {{ minio_url }} {{ minio_root_user }} {{ minio_root_password }}"
  register: alias_command
  changed_when: false
  failed_when: '"Added `" + minio_alias + "` successfully" not in alias_command.stdout'

- name: Create Minio Buckets
  include_tasks: create_minio_buckets.yml
  when: minio_buckets | length > 0
  