---

- name: Compose the Minio client download base url
  set_fact:
    _minio_client_download_url: "https://dl.minio.io/client/mc/release/linux-{{ go_arch }}/archive/mc.{{ minio_mc_version }}"

- name: Get the MinIO client checksum (remote curl)
  shell: "curl -sL {{ _minio_client_download_url }}.sha256sum | awk '{print $1}'"
  register: mc_checksum
  changed_when: false

- name: Store checksum fact
  set_fact:
    _minio_client_checksum: "{{ mc_checksum.stdout }}"

- name: Download the Minio client
  get_url:
    url: "{{ _minio_client_download_url }}"
    dest: "{{ minio_client_bin }}"
    owner: "root"
    group: "root"
    mode: 0755
    checksum: "sha256:{{ _minio_client_checksum }}"
  register: _download_client
  until: _download_client is succeeded
  retries: 5
  delay: 2
