---
- name: Определить роль хоста в развертывании
  ansible.builtin.set_fact:
    minio_is_lb: "{{ (minio_lb_group in group_names) | bool }}"

- name: Выполнить сценарий для балансировщика
  ansible.builtin.include_tasks: minio_lb.yml
  when:
    - minio_enable_lb | default(true) | bool
    - minio_is_lb | bool

- name: Завершить выполнение задач на балансировщике
  ansible.builtin.meta: end_host
  when:
    - minio_is_lb | bool

- name: Выполнить сценарий узла хранилища
  ansible.builtin.include_tasks: minio_nodes.yml
