---
- name: Detect host role
  ansible.builtin.set_fact:
    minio_is_lb: "{{ (minio_lb_group in group_names) | bool }}"

- name: Run LB scenario
  ansible.builtin.include_tasks: minio_lb.yml
  when:
    - minio_enable_lb | default(true) | bool
    - minio_is_lb | bool

- name: Stop role on LB host
  ansible.builtin.meta: end_host
  when:
    - minio_is_lb | bool

- name: Run nodes scenario
  ansible.builtin.include_tasks: minio_nodes.yml
