---
- name: Установить nginx для балансировки MinIO
  ansible.builtin.include_tasks: minio_lb_install.yml

- name: Сформировать список бэкендов для nginx
  ansible.builtin.include_tasks: minio_lb_build_backends.yml

- name: Применить конфигурацию nginx для MinIO
  ansible.builtin.include_tasks: minio_lb_configure.yml

- name: Выполнить отложенные обработчики перед выходом
  ansible.builtin.meta: flush_handlers
