---
- name: Derive datadirs from minio_extra_disks (force override)
  ansible.builtin.set_fact:
    minio_server_datadirs: "{{ minio_extra_disks | map(attribute='mount') | list }}"
  when: (minio_extra_disks | default([])) | length > 0
  changed_when: false

- name: Ensure minio group
  ansible.builtin.group:
    name: "{{ minio_group }}"
    state: present

- name: Ensure minio user
  ansible.builtin.user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: true
    create_home: false
    shell: /usr/sbin/nologin

- name: Preconf | Prepare data disks
  ansible.builtin.include_tasks: prepare_disks.yml

- name: Install / configure MinIO server (package)
  ansible.builtin.include_tasks: install_server.yml
  when: minio_install_server | bool

- name: Configure MinIO server
  ansible.builtin.include_tasks: configure_server.yml
  when: minio_install_server | bool

- name: Install / configure MinIO client
  ansible.builtin.include_tasks: install_client.yml
  when: minio_install_client | bool

- name: Report stats
  ansible.builtin.include_tasks: stats.yml