---
- name: Сформировать конфигурацию nginx для MinIO
  ansible.builtin.template:
    src: minio_lb.nginx.j2
    dest: "{{ '/etc/nginx/conf.d/minio_lb.conf' if (ansible_distribution.split(' ') | first | lower == 'red') else minio_lb_nginx_conf }}"
    owner: root
    group: root
    mode: "0644"
  notify: Перезапустить службу nginx

- name: Ubuntu | Удалить стандартный сайт nginx при наличии
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: ansible_os_family == 'Debian'

- name: РЕД ОС 8 | Открыть порты балансировщика в Firewalld
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ minio_lb_api_port | default('9000') }}"
    - "{{ minio_lb_console_port | default('9001') }}"
  when: ansible_distribution.split(' ') | first | lower == 'red'
  ignore_errors: true

- name: РЕД ОС 8 | Разрешить Nginx слушать порт Console (9001) в SELinux
  community.general.seport:
    ports: "9001"
    proto: tcp
    setype: http_port_t
    state: present
  when: ansible_distribution.split(' ') | first | lower == 'red'

- name: РЕД ОС 8 | Разрешить Nginx слушать порт API (9000) в SELinux
  community.general.seport:
    ports: "9000"
    proto: tcp
    setype: http_port_t
    state: present
  when: ansible_distribution.split(' ') | first | lower == 'red'

- name: РЕД ОС 8 | Разрешить Nginx проксировать трафик к бэкендам MinIO
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when: ansible_distribution.split(' ') | first | lower == 'red'

- name: РЕД ОС 8 | Отключить дефолтный welcome-конфиг nginx (при наличии)
  ansible.builtin.file:
    path: /etc/nginx/conf.d/welcome.conf
    state: absent
  when: ansible_distribution.split(' ') | first | lower == 'red'
  notify: Перезапустить службу nginx
