---
- name: LB | template nginx config
  ansible.builtin.template:
    src: minio_lb.nginx.j2
    dest: "{{ minio_lb_nginx_conf }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx

- name: LB | remove default site if exists
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  ignore_errors: true
