# tasks/prepare_single_disk.yml
# item.key  -> устройство (/dev/vdb)
# item.value-> точка монтирования (/app/d1)

- name: Disk | Ensure mountpoint dir
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0750"

- name: FS | Detect current fstype
  ansible.builtin.command: blkid -s TYPE -o value {{ item.key }}
  register: _fstype
  changed_when: false
  failed_when: false

- name: FS | Create XFS if needed (reflink=0)
  community.general.filesystem:
    fstype: xfs
    dev: "{{ item.key }}"
    opts: "-m reflink=0"
    force: false
  when: _fstype.stdout != 'xfs'

- name: FS | Get UUID
  ansible.builtin.command: blkid -s UUID -o value {{ item.key }}
  register: _uuid
  changed_when: false

- name: Mount | Mount and persist in fstab
  ansible.posix.mount:
    path: "{{ item.value }}"
    src: "{{ 'UUID=' + _uuid.stdout if _uuid.stdout | length > 0 else item.key }}"
    fstype: xfs
    opts: "noatime,nodiratime"
    state: mounted
