---
- name: "Disk | Размонтировать, если вдруг смонтирован"
  shell: |
    set -euo pipefail
    dev="{{ item.key }}"
    mnts=$(lsblk -nr -o MOUNTPOINT "$dev" | awk 'NF' || true)
    if [ -n "$mnts" ]; then
      while read -r m; do umount -f "$m" || true; done <<< "$mnts"
    fi
  args:
    executable: /bin/bash

- name: "Disk | WipeFS (опц.)"
  command: "wipefs -af {{ item.key }}"
  when: minio_preconf_wipe_disks | default(false)

- name: "FS | Создать XFS (reflink=0) на устройстве"
  filesystem:
    fstype: xfs
    dev: "{{ item.key }}"
    force: true
    opts: "-m reflink=0"

- name: "FS | Создать каталог монтирования"
  file:
    path: "{{ item.value }}"
    state: directory
    owner: "{{ minio_user | default('minio') }}"
    group: "{{ minio_group | default('minio') }}"
    mode: "0750"

- name: "FS | Получить UUID"
  command: "blkid -o value -s UUID {{ item.key }}"
  register: _blk
  changed_when: false

- name: "Mount | Прописать в fstab и смонтировать"
  mount:
    path: "{{ item.value }}"
    src: "UUID={{ _blk.stdout | trim }}"
    fstype: xfs
    opts: "defaults,noatime,nodiratime"
    state: mounted
