---
- name: Перечитать unit MinIO
  ansible.builtin.systemd:
    name: minio
    daemon_reload: true

- name: Перезапустить службу MinIO
  ansible.builtin.systemd:
    name: minio
    state: restarted
    daemon_reload: true
  when: minio_autostart | default(true)

- name: Перезапустить службу nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
