---
- name: Reload minio systemd
  systemd:
    name: minio
    daemon_reload: true

- name: Restart minio
  service:
    name: minio
    state: restarted

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
